# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import demo_pb2 as demo__pb2


class ActivityStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateCoupon = channel.unary_unary(
        '/demo.Activity/CreateCoupon',
        request_serializer=demo__pb2.CreateCouponReq.SerializeToString,
        response_deserializer=demo__pb2.CreateCouponResp.FromString,
        )
    self.SendCoupon = channel.unary_unary(
        '/demo.Activity/SendCoupon',
        request_serializer=demo__pb2.SendCouponReq.SerializeToString,
        response_deserializer=demo__pb2.SendCouponResp.FromString,
        )
    self.UseCoupon = channel.unary_unary(
        '/demo.Activity/UseCoupon',
        request_serializer=demo__pb2.UseCouponReq.SerializeToString,
        response_deserializer=demo__pb2.UseCouponResp.FromString,
        )


class ActivityServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateCoupon(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendCoupon(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UseCoupon(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ActivityServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateCoupon': grpc.unary_unary_rpc_method_handler(
          servicer.CreateCoupon,
          request_deserializer=demo__pb2.CreateCouponReq.FromString,
          response_serializer=demo__pb2.CreateCouponResp.SerializeToString,
      ),
      'SendCoupon': grpc.unary_unary_rpc_method_handler(
          servicer.SendCoupon,
          request_deserializer=demo__pb2.SendCouponReq.FromString,
          response_serializer=demo__pb2.SendCouponResp.SerializeToString,
      ),
      'UseCoupon': grpc.unary_unary_rpc_method_handler(
          servicer.UseCoupon,
          request_deserializer=demo__pb2.UseCouponReq.FromString,
          response_serializer=demo__pb2.UseCouponResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'demo.Activity', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
