# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo.proto',
  package='demo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndemo.proto\x12\x04\x64\x65mo\"D\n\nRequestCtx\x12\x10\n\x08\x62usiness\x18\x01 \x01(\t\x12\x0f\n\x07shop_id\x18\x02 \x01(\x05\x12\x13\n\x0bpassport_id\x18\x03 \x01(\x05\"&\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"@\n\x0f\x43reateCouponReq\x12\x1d\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x10.demo.RequestCtx\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"@\n\x10\x43reateCouponResp\x12\x18\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x0b.demo.Error\x12\x12\n\ncoupon_num\x18\x02 \x01(\t\"`\n\rSendCouponReq\x12\x1d\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x10.demo.RequestCtx\x12\x12\n\ncoupon_num\x18\x02 \x01(\t\x12\x1c\n\x14receiver_passport_id\x18\x03 \x01(\x05\"*\n\x0eSendCouponResp\x12\x18\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x0b.demo.Error\"W\n\x0cUseCouponReq\x12\x1d\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x10.demo.RequestCtx\x12\x12\n\ncoupon_num\x18\x02 \x01(\t\x12\x14\n\x0corder_amount\x18\x03 \x01(\x05\"B\n\rUseCouponResp\x12\x18\n\x03\x65rr\x18\x01 \x01(\x0b\x32\x0b.demo.Error\x12\x17\n\x0f\x64iscount_amount\x18\x02 \x01(\x05\x32\xbe\x01\n\x08\x41\x63tivity\x12?\n\x0c\x43reateCoupon\x12\x15.demo.CreateCouponReq\x1a\x16.demo.CreateCouponResp\"\x00\x12\x39\n\nSendCoupon\x12\x13.demo.SendCouponReq\x1a\x14.demo.SendCouponResp\"\x00\x12\x36\n\tUseCoupon\x12\x12.demo.UseCouponReq\x1a\x13.demo.UseCouponResp\"\x00\x62\x06proto3')
)




_REQUESTCTX = _descriptor.Descriptor(
  name='RequestCtx',
  full_name='demo.RequestCtx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='business', full_name='demo.RequestCtx.business', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shop_id', full_name='demo.RequestCtx.shop_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passport_id', full_name='demo.RequestCtx.passport_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=88,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='demo.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='demo.Error.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='demo.Error.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=128,
)


_CREATECOUPONREQ = _descriptor.Descriptor(
  name='CreateCouponReq',
  full_name='demo.CreateCouponReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ctx', full_name='demo.CreateCouponReq.ctx', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='demo.CreateCouponReq.amount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=194,
)


_CREATECOUPONRESP = _descriptor.Descriptor(
  name='CreateCouponResp',
  full_name='demo.CreateCouponResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='demo.CreateCouponResp.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coupon_num', full_name='demo.CreateCouponResp.coupon_num', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=260,
)


_SENDCOUPONREQ = _descriptor.Descriptor(
  name='SendCouponReq',
  full_name='demo.SendCouponReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ctx', full_name='demo.SendCouponReq.ctx', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coupon_num', full_name='demo.SendCouponReq.coupon_num', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_passport_id', full_name='demo.SendCouponReq.receiver_passport_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=358,
)


_SENDCOUPONRESP = _descriptor.Descriptor(
  name='SendCouponResp',
  full_name='demo.SendCouponResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='demo.SendCouponResp.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=402,
)


_USECOUPONREQ = _descriptor.Descriptor(
  name='UseCouponReq',
  full_name='demo.UseCouponReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ctx', full_name='demo.UseCouponReq.ctx', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coupon_num', full_name='demo.UseCouponReq.coupon_num', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_amount', full_name='demo.UseCouponReq.order_amount', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=491,
)


_USECOUPONRESP = _descriptor.Descriptor(
  name='UseCouponResp',
  full_name='demo.UseCouponResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='demo.UseCouponResp.err', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='discount_amount', full_name='demo.UseCouponResp.discount_amount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=559,
)

_CREATECOUPONREQ.fields_by_name['ctx'].message_type = _REQUESTCTX
_CREATECOUPONRESP.fields_by_name['err'].message_type = _ERROR
_SENDCOUPONREQ.fields_by_name['ctx'].message_type = _REQUESTCTX
_SENDCOUPONRESP.fields_by_name['err'].message_type = _ERROR
_USECOUPONREQ.fields_by_name['ctx'].message_type = _REQUESTCTX
_USECOUPONRESP.fields_by_name['err'].message_type = _ERROR
DESCRIPTOR.message_types_by_name['RequestCtx'] = _REQUESTCTX
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.message_types_by_name['CreateCouponReq'] = _CREATECOUPONREQ
DESCRIPTOR.message_types_by_name['CreateCouponResp'] = _CREATECOUPONRESP
DESCRIPTOR.message_types_by_name['SendCouponReq'] = _SENDCOUPONREQ
DESCRIPTOR.message_types_by_name['SendCouponResp'] = _SENDCOUPONRESP
DESCRIPTOR.message_types_by_name['UseCouponReq'] = _USECOUPONREQ
DESCRIPTOR.message_types_by_name['UseCouponResp'] = _USECOUPONRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestCtx = _reflection.GeneratedProtocolMessageType('RequestCtx', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCTX,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.RequestCtx)
  })
_sym_db.RegisterMessage(RequestCtx)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.Error)
  })
_sym_db.RegisterMessage(Error)

CreateCouponReq = _reflection.GeneratedProtocolMessageType('CreateCouponReq', (_message.Message,), {
  'DESCRIPTOR' : _CREATECOUPONREQ,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.CreateCouponReq)
  })
_sym_db.RegisterMessage(CreateCouponReq)

CreateCouponResp = _reflection.GeneratedProtocolMessageType('CreateCouponResp', (_message.Message,), {
  'DESCRIPTOR' : _CREATECOUPONRESP,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.CreateCouponResp)
  })
_sym_db.RegisterMessage(CreateCouponResp)

SendCouponReq = _reflection.GeneratedProtocolMessageType('SendCouponReq', (_message.Message,), {
  'DESCRIPTOR' : _SENDCOUPONREQ,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.SendCouponReq)
  })
_sym_db.RegisterMessage(SendCouponReq)

SendCouponResp = _reflection.GeneratedProtocolMessageType('SendCouponResp', (_message.Message,), {
  'DESCRIPTOR' : _SENDCOUPONRESP,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.SendCouponResp)
  })
_sym_db.RegisterMessage(SendCouponResp)

UseCouponReq = _reflection.GeneratedProtocolMessageType('UseCouponReq', (_message.Message,), {
  'DESCRIPTOR' : _USECOUPONREQ,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.UseCouponReq)
  })
_sym_db.RegisterMessage(UseCouponReq)

UseCouponResp = _reflection.GeneratedProtocolMessageType('UseCouponResp', (_message.Message,), {
  'DESCRIPTOR' : _USECOUPONRESP,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.UseCouponResp)
  })
_sym_db.RegisterMessage(UseCouponResp)



_ACTIVITY = _descriptor.ServiceDescriptor(
  name='Activity',
  full_name='demo.Activity',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=562,
  serialized_end=752,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateCoupon',
    full_name='demo.Activity.CreateCoupon',
    index=0,
    containing_service=None,
    input_type=_CREATECOUPONREQ,
    output_type=_CREATECOUPONRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendCoupon',
    full_name='demo.Activity.SendCoupon',
    index=1,
    containing_service=None,
    input_type=_SENDCOUPONREQ,
    output_type=_SENDCOUPONRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UseCoupon',
    full_name='demo.Activity.UseCoupon',
    index=2,
    containing_service=None,
    input_type=_USECOUPONREQ,
    output_type=_USECOUPONRESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACTIVITY)

DESCRIPTOR.services_by_name['Activity'] = _ACTIVITY

# @@protoc_insertion_point(module_scope)
