// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package demo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求上下文
type RequestCtx struct {
	Business             string   `protobuf:"bytes,1,opt,name=business,proto3" json:"business,omitempty"`
	ShopId               int32    `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	PassportId           int32    `protobuf:"varint,3,opt,name=passport_id,json=passportId,proto3" json:"passport_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestCtx) Reset()         { *m = RequestCtx{} }
func (m *RequestCtx) String() string { return proto.CompactTextString(m) }
func (*RequestCtx) ProtoMessage()    {}
func (*RequestCtx) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *RequestCtx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestCtx.Unmarshal(m, b)
}
func (m *RequestCtx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestCtx.Marshal(b, m, deterministic)
}
func (m *RequestCtx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestCtx.Merge(m, src)
}
func (m *RequestCtx) XXX_Size() int {
	return xxx_messageInfo_RequestCtx.Size(m)
}
func (m *RequestCtx) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestCtx.DiscardUnknown(m)
}

var xxx_messageInfo_RequestCtx proto.InternalMessageInfo

func (m *RequestCtx) GetBusiness() string {
	if m != nil {
		return m.Business
	}
	return ""
}

func (m *RequestCtx) GetShopId() int32 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *RequestCtx) GetPassportId() int32 {
	if m != nil {
		return m.PassportId
	}
	return 0
}

// 错误消息
type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 创建优惠券请求
type CreateCouponReq struct {
	Ctx                  *RequestCtx `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Amount               int32       `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateCouponReq) Reset()         { *m = CreateCouponReq{} }
func (m *CreateCouponReq) String() string { return proto.CompactTextString(m) }
func (*CreateCouponReq) ProtoMessage()    {}
func (*CreateCouponReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{2}
}

func (m *CreateCouponReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCouponReq.Unmarshal(m, b)
}
func (m *CreateCouponReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCouponReq.Marshal(b, m, deterministic)
}
func (m *CreateCouponReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCouponReq.Merge(m, src)
}
func (m *CreateCouponReq) XXX_Size() int {
	return xxx_messageInfo_CreateCouponReq.Size(m)
}
func (m *CreateCouponReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCouponReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCouponReq proto.InternalMessageInfo

func (m *CreateCouponReq) GetCtx() *RequestCtx {
	if m != nil {
		return m.Ctx
	}
	return nil
}

func (m *CreateCouponReq) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// 创建优惠券响应
type CreateCouponResp struct {
	Err                  *Error   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	CouponNum            string   `protobuf:"bytes,2,opt,name=coupon_num,json=couponNum,proto3" json:"coupon_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCouponResp) Reset()         { *m = CreateCouponResp{} }
func (m *CreateCouponResp) String() string { return proto.CompactTextString(m) }
func (*CreateCouponResp) ProtoMessage()    {}
func (*CreateCouponResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{3}
}

func (m *CreateCouponResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCouponResp.Unmarshal(m, b)
}
func (m *CreateCouponResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCouponResp.Marshal(b, m, deterministic)
}
func (m *CreateCouponResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCouponResp.Merge(m, src)
}
func (m *CreateCouponResp) XXX_Size() int {
	return xxx_messageInfo_CreateCouponResp.Size(m)
}
func (m *CreateCouponResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCouponResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCouponResp proto.InternalMessageInfo

func (m *CreateCouponResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *CreateCouponResp) GetCouponNum() string {
	if m != nil {
		return m.CouponNum
	}
	return ""
}

// 赠送优惠券请求
type SendCouponReq struct {
	Ctx                  *RequestCtx `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	CouponNum            string      `protobuf:"bytes,2,opt,name=coupon_num,json=couponNum,proto3" json:"coupon_num,omitempty"`
	ReceiverPassportId   int32       `protobuf:"varint,3,opt,name=receiver_passport_id,json=receiverPassportId,proto3" json:"receiver_passport_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SendCouponReq) Reset()         { *m = SendCouponReq{} }
func (m *SendCouponReq) String() string { return proto.CompactTextString(m) }
func (*SendCouponReq) ProtoMessage()    {}
func (*SendCouponReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{4}
}

func (m *SendCouponReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCouponReq.Unmarshal(m, b)
}
func (m *SendCouponReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCouponReq.Marshal(b, m, deterministic)
}
func (m *SendCouponReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCouponReq.Merge(m, src)
}
func (m *SendCouponReq) XXX_Size() int {
	return xxx_messageInfo_SendCouponReq.Size(m)
}
func (m *SendCouponReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCouponReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendCouponReq proto.InternalMessageInfo

func (m *SendCouponReq) GetCtx() *RequestCtx {
	if m != nil {
		return m.Ctx
	}
	return nil
}

func (m *SendCouponReq) GetCouponNum() string {
	if m != nil {
		return m.CouponNum
	}
	return ""
}

func (m *SendCouponReq) GetReceiverPassportId() int32 {
	if m != nil {
		return m.ReceiverPassportId
	}
	return 0
}

// 赠送优惠券请求
type SendCouponResp struct {
	Err                  *Error   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendCouponResp) Reset()         { *m = SendCouponResp{} }
func (m *SendCouponResp) String() string { return proto.CompactTextString(m) }
func (*SendCouponResp) ProtoMessage()    {}
func (*SendCouponResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{5}
}

func (m *SendCouponResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCouponResp.Unmarshal(m, b)
}
func (m *SendCouponResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCouponResp.Marshal(b, m, deterministic)
}
func (m *SendCouponResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCouponResp.Merge(m, src)
}
func (m *SendCouponResp) XXX_Size() int {
	return xxx_messageInfo_SendCouponResp.Size(m)
}
func (m *SendCouponResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCouponResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendCouponResp proto.InternalMessageInfo

func (m *SendCouponResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

// 使用优惠券请求
type UseCouponReq struct {
	Ctx                  *RequestCtx `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	CouponNum            string      `protobuf:"bytes,2,opt,name=coupon_num,json=couponNum,proto3" json:"coupon_num,omitempty"`
	OrderAmount          int32       `protobuf:"varint,3,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UseCouponReq) Reset()         { *m = UseCouponReq{} }
func (m *UseCouponReq) String() string { return proto.CompactTextString(m) }
func (*UseCouponReq) ProtoMessage()    {}
func (*UseCouponReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{6}
}

func (m *UseCouponReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseCouponReq.Unmarshal(m, b)
}
func (m *UseCouponReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseCouponReq.Marshal(b, m, deterministic)
}
func (m *UseCouponReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseCouponReq.Merge(m, src)
}
func (m *UseCouponReq) XXX_Size() int {
	return xxx_messageInfo_UseCouponReq.Size(m)
}
func (m *UseCouponReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UseCouponReq.DiscardUnknown(m)
}

var xxx_messageInfo_UseCouponReq proto.InternalMessageInfo

func (m *UseCouponReq) GetCtx() *RequestCtx {
	if m != nil {
		return m.Ctx
	}
	return nil
}

func (m *UseCouponReq) GetCouponNum() string {
	if m != nil {
		return m.CouponNum
	}
	return ""
}

func (m *UseCouponReq) GetOrderAmount() int32 {
	if m != nil {
		return m.OrderAmount
	}
	return 0
}

// 使用优惠券响应
type UseCouponResp struct {
	Err                  *Error   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	DiscountAmount       int32    `protobuf:"varint,2,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseCouponResp) Reset()         { *m = UseCouponResp{} }
func (m *UseCouponResp) String() string { return proto.CompactTextString(m) }
func (*UseCouponResp) ProtoMessage()    {}
func (*UseCouponResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{7}
}

func (m *UseCouponResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseCouponResp.Unmarshal(m, b)
}
func (m *UseCouponResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseCouponResp.Marshal(b, m, deterministic)
}
func (m *UseCouponResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseCouponResp.Merge(m, src)
}
func (m *UseCouponResp) XXX_Size() int {
	return xxx_messageInfo_UseCouponResp.Size(m)
}
func (m *UseCouponResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UseCouponResp.DiscardUnknown(m)
}

var xxx_messageInfo_UseCouponResp proto.InternalMessageInfo

func (m *UseCouponResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *UseCouponResp) GetDiscountAmount() int32 {
	if m != nil {
		return m.DiscountAmount
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestCtx)(nil), "demo.RequestCtx")
	proto.RegisterType((*Error)(nil), "demo.Error")
	proto.RegisterType((*CreateCouponReq)(nil), "demo.CreateCouponReq")
	proto.RegisterType((*CreateCouponResp)(nil), "demo.CreateCouponResp")
	proto.RegisterType((*SendCouponReq)(nil), "demo.SendCouponReq")
	proto.RegisterType((*SendCouponResp)(nil), "demo.SendCouponResp")
	proto.RegisterType((*UseCouponReq)(nil), "demo.UseCouponReq")
	proto.RegisterType((*UseCouponResp)(nil), "demo.UseCouponResp")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xcf, 0xaf, 0xd2, 0x40,
	0x10, 0xb6, 0xf2, 0xe0, 0xbd, 0x4e, 0x79, 0x3f, 0x32, 0x0f, 0x91, 0x34, 0x21, 0xe2, 0x5e, 0xe4,
	0x84, 0x06, 0xa3, 0x89, 0x27, 0x43, 0x88, 0x07, 0x0e, 0x1a, 0xb2, 0xc6, 0x78, 0x6c, 0x4a, 0x77,
	0xa2, 0x3d, 0xb4, 0x5b, 0x76, 0xb7, 0x04, 0xef, 0xfe, 0x5d, 0xfe, 0x6d, 0xa6, 0xbb, 0x14, 0x8a,
	0x18, 0x89, 0xc9, 0xbb, 0xcd, 0x7c, 0x33, 0xf3, 0xf5, 0x9b, 0x6f, 0xba, 0x00, 0x82, 0x32, 0x39,
	0x29, 0x94, 0x34, 0x12, 0x2f, 0xaa, 0x98, 0xad, 0x00, 0x38, 0xad, 0x4b, 0xd2, 0x66, 0x6e, 0xb6,
	0x18, 0xc2, 0xd5, 0xaa, 0xd4, 0x69, 0x4e, 0x5a, 0x0f, 0xbc, 0x91, 0x37, 0xf6, 0xf9, 0x3e, 0xc7,
	0xa7, 0x70, 0xa9, 0xbf, 0xcb, 0x22, 0x4a, 0xc5, 0xe0, 0xf1, 0xc8, 0x1b, 0xb7, 0x79, 0xa7, 0x4a,
	0x17, 0x02, 0x9f, 0x41, 0x50, 0xc4, 0x5a, 0x17, 0x52, 0x99, 0xaa, 0xd8, 0xb2, 0x45, 0xa8, 0xa1,
	0x85, 0x60, 0x6f, 0xa0, 0xfd, 0x41, 0x29, 0xa9, 0x10, 0xe1, 0x22, 0x91, 0x82, 0x2c, 0x75, 0x9b,
	0xdb, 0x18, 0x07, 0x70, 0x99, 0x91, 0xd6, 0xf1, 0x37, 0xb2, 0xb4, 0x3e, 0xaf, 0x53, 0xf6, 0x11,
	0x6e, 0xe7, 0x8a, 0x62, 0x43, 0x73, 0x59, 0x16, 0x32, 0xe7, 0xb4, 0x46, 0x06, 0xad, 0xc4, 0x6c,
	0xed, 0x7c, 0x30, 0xbd, 0x9b, 0xd8, 0x6d, 0x0e, 0xf2, 0x79, 0x55, 0xc4, 0x3e, 0x74, 0xe2, 0x4c,
	0x96, 0xb9, 0xa9, 0x65, 0xba, 0x8c, 0x2d, 0xe1, 0xee, 0x98, 0x4e, 0x17, 0x38, 0x84, 0x16, 0x29,
	0xb5, 0xe3, 0x0b, 0x1c, 0x9f, 0x95, 0xca, 0x2b, 0x1c, 0x87, 0x00, 0x89, 0x6d, 0x8e, 0xf2, 0x32,
	0xdb, 0xc9, 0xf3, 0x1d, 0xf2, 0xa9, 0xcc, 0xd8, 0x4f, 0x0f, 0xae, 0x3f, 0x53, 0x2e, 0xfe, 0x4f,
	0xdf, 0xbf, 0x49, 0xf1, 0x15, 0xf4, 0x14, 0x25, 0x94, 0x6e, 0x48, 0x45, 0xa7, 0xb6, 0x62, 0x5d,
	0x5b, 0x1e, 0xec, 0x7d, 0x09, 0x37, 0x4d, 0x15, 0x67, 0xd7, 0x62, 0x06, 0xba, 0x5f, 0x34, 0x3d,
	0xa8, 0xea, 0xe7, 0xd0, 0x95, 0x4a, 0x90, 0x8a, 0x76, 0xd6, 0x3b, 0xb5, 0x81, 0xc5, 0x66, 0xce,
	0xff, 0xaf, 0x70, 0xdd, 0xf8, 0xea, 0x79, 0xf3, 0x5f, 0xc0, 0xad, 0x48, 0x75, 0x52, 0xcd, 0x46,
	0x47, 0x07, 0xbd, 0xa9, 0x61, 0x47, 0x3c, 0xfd, 0xe5, 0xc1, 0xd5, 0x2c, 0x31, 0xe9, 0x26, 0x35,
	0x3f, 0xf0, 0x3d, 0x74, 0x9b, 0x57, 0xc6, 0x27, 0x8e, 0xf7, 0x8f, 0x1f, 0x29, 0xec, 0xff, 0x0d,
	0xd6, 0x05, 0x7b, 0x84, 0xef, 0x00, 0x0e, 0x6e, 0xe2, 0xbd, 0xeb, 0x3b, 0xba, 0x72, 0xd8, 0x3b,
	0x05, 0xed, 0xe8, 0x5b, 0xf0, 0xf7, 0x1b, 0x22, 0xba, 0xa6, 0xa6, 0xd1, 0xe1, 0xfd, 0x09, 0x56,
	0xcd, 0xad, 0x3a, 0xf6, 0x41, 0xbe, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x0f, 0x93, 0xa0,
	0x9e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ActivityClient is the client API for Activity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActivityClient interface {
	CreateCoupon(ctx context.Context, in *CreateCouponReq, opts ...grpc.CallOption) (*CreateCouponResp, error)
	SendCoupon(ctx context.Context, in *SendCouponReq, opts ...grpc.CallOption) (*SendCouponResp, error)
	UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*UseCouponResp, error)
}

type activityClient struct {
	cc *grpc.ClientConn
}

func NewActivityClient(cc *grpc.ClientConn) ActivityClient {
	return &activityClient{cc}
}

func (c *activityClient) CreateCoupon(ctx context.Context, in *CreateCouponReq, opts ...grpc.CallOption) (*CreateCouponResp, error) {
	out := new(CreateCouponResp)
	err := c.cc.Invoke(ctx, "/demo.Activity/CreateCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) SendCoupon(ctx context.Context, in *SendCouponReq, opts ...grpc.CallOption) (*SendCouponResp, error) {
	out := new(SendCouponResp)
	err := c.cc.Invoke(ctx, "/demo.Activity/SendCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*UseCouponResp, error) {
	out := new(UseCouponResp)
	err := c.cc.Invoke(ctx, "/demo.Activity/UseCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityServer is the server API for Activity service.
type ActivityServer interface {
	CreateCoupon(context.Context, *CreateCouponReq) (*CreateCouponResp, error)
	SendCoupon(context.Context, *SendCouponReq) (*SendCouponResp, error)
	UseCoupon(context.Context, *UseCouponReq) (*UseCouponResp, error)
}

// UnimplementedActivityServer can be embedded to have forward compatible implementations.
type UnimplementedActivityServer struct {
}

func (*UnimplementedActivityServer) CreateCoupon(ctx context.Context, req *CreateCouponReq) (*CreateCouponResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCoupon not implemented")
}
func (*UnimplementedActivityServer) SendCoupon(ctx context.Context, req *SendCouponReq) (*SendCouponResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCoupon not implemented")
}
func (*UnimplementedActivityServer) UseCoupon(ctx context.Context, req *UseCouponReq) (*UseCouponResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseCoupon not implemented")
}

func RegisterActivityServer(s *grpc.Server, srv ActivityServer) {
	s.RegisterService(&_Activity_serviceDesc, srv)
}

func _Activity_CreateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).CreateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo.Activity/CreateCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).CreateCoupon(ctx, req.(*CreateCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_SendCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).SendCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo.Activity/SendCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).SendCoupon(ctx, req.(*SendCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_UseCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).UseCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo.Activity/UseCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).UseCoupon(ctx, req.(*UseCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Activity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "demo.Activity",
	HandlerType: (*ActivityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCoupon",
			Handler:    _Activity_CreateCoupon_Handler,
		},
		{
			MethodName: "SendCoupon",
			Handler:    _Activity_SendCoupon_Handler,
		},
		{
			MethodName: "UseCoupon",
			Handler:    _Activity_UseCoupon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}
